name: angel_data_store
version: 0.0.0
description: package:data_store-enabled services for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/data_store.git
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0-dev
  data_store:
    path: ../data_store
dev_dependencies:
  angel_test: ^1.0.0-dev
  test: ^0.12.0
