name: angel_query_builder
version: 0.0.0
description: package:query_builder-enabled services for the Angel framework.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/data_store.git
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_framework: ^1.0.0
  query_builder: ^0.0.0
dev_dependencies:
  angel_diagnostics: ^1.0.0
  angel_test: ^1.0.0
  query_builder_in_memory: ^0.0.0
  test: ^0.12.0
dependency_overrides:
  query_builder:
    path: ../query_builder
  query_builder_in_memory:
    path: ../in_memory
