name: query_builder_postgres
description: PostgreSQL support for for package:query_builder.
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
dependencies:
  postgres: ^0.9.5
  query_builder: ^0.0.0
  query_builder_sql: ^0.0.0
dependency_overrides:
  query_builder:
    path: ../query_builder
  query_builder_sql:
    path: ../sql