name: query_builder_mongo
description: MongoDB repository class for package:query_builder.
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
dependencies:
  mongo_dart: ^0.2.7
  mutex: ^0.0.1
  query_builder: ^0.0.0
dependency_overrides:
  query_builder:
    path: ../query_builder