name: query_builder_sql
description: Common functionality for SQL database use with package:query_builder.
version: 1.0.0-alpha
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.19.0"
dependencies:
  query_builder: ^0.0.0
  tuple: ^1.0.0
dev_dependencies:
  test: ^0.12.0
dependency_overrides:
  query_builder:
    path: ../query_builder