name: query_builder_sql
description: Common functionality for SQL database use with package:query_builder.
version: 1.0.0-alpha
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/query_builder
environment:
  sdk: ">=1.19.0"
dependencies:
  query_builder: ^0.0.2
  tuple: ^1.0.0
dev_dependencies:
  test: ^0.12.0